source 'https://supermarket.chef.io'

cookbook 'apt'
cookbook 'git'
cookbook 'vim'
cookbook 'apache2'
cookbook 'mysql', '~> 6.0'
cookbook 'php', :git => 'https://github.com/priestjim/chef-php'
cookbook 'composer', :git => 'https://github.com/zircote/chef-composer'
cookbook 'xdebug', :git => 'https://github.com/escapestudios-cookbooks/xdebug'
cookbook 'base', :path => 'chef/cookbooks/base'
